version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache-morph
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    depends_on:
      - db-morph
    volumes:
      - ./app/:/var/www/
      - ./app/public:/var/www/html/
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - 8000:80
    environment:
      - PHP_IDE_CONFIG=serverName=morph-play-space

  db:
    container_name: db-morph
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: morph-play-space
      #MYSQL_USER: admin
      #MYSQL_PASSWORD: adminpass
    ports:
      - "9906:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: db-morph
    depends_on:
      - db-morph

  #Laravel App
  app:
    build:
      args:
        user: morph
        uid: 1000
      context: ./docker/php
      dockerfile: Dockerfile
    image: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html/
    volumes:
      - ./app/:/var/www/html/
